server:
  port: 81

service-url:
  nacos-pay-service: http://nacos-pay

spring:
  application:
    name: nacos-web
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.42:8888
#        server-addr: 127.0.0.1:8848