server:
  port: 9003
spring:
  application:
    name: nacos-pay
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.116.125:1111
  datasource:
    url: jdbc:mysql://192.168.116.125:3306/nacos_cloud?useUnicode=true&characterEncoding=utf8mb4&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
#        server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/mq/nacos/mapper/xml/*.xml
  type-aliases-package: com.mq.nacos.entity
  global-config:
      db-config:
        logic-delete-value: 1
        logic-not-delete-value: 0