server:
  port: 8080
spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/

  application:
    name: nacos-upload
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.42:8888
